### ISSUE TITLE
SSS test data does not open in graph or mne_browse_raw

### ISSUE THREAD

**Issue by jhouck** [mne-tools/mne-testing-data#1]
I'm having trouble opening the two SSS raw testing files (test_move_anon_raw.fif and test_move_anon_raw_sss.fif).  A fairly recent build of mne_browse_raw (2.7.4.2448) complains that each file "does not start properly!" while Neuromag graph complains that "FIFF file should start with FIFF_FILE_ID!".  Maxfilter -history reports "ERROR: Cannot open channel info file test_move_anon_raw_sss.fif! Cannot process data (exit value = 3)."  Just a heads up.

**Comment by Eric89GXL** [comment]
Can you read it with mne-python? I wonder if the file is somehow broken on your system. If it reads okay with mne-python, it suggests we are not writing out some tag that we otherwise should be.

**Comment by jhouck** [comment]
Well, that was dumb.  Unzipping the file put me over quota, and some of the files were truncated. After clearing some space, I can open test_move_anon_raw_sss.fif.  

With  test_move_anon_raw.fif, Graph warns me that it contains Maxshield data, but allows me to continue; mne_browse_raw says that there is "No raw data in this file."  Mne-python will open it provided that I add allow_maxshield=True to the Raw command; otherwise it errors out with a message that there is "No raw data in /tmp/test_move_anon_raw.fif".

**Comment by Eric89GXL** [comment]
Cool. Note that mne_browse_raw has an --allowmaxshield option that will
allow you to view the file as well.
