### ISSUE TITLE
Anonymized data

### ISSUE THREAD

**Issue by wronk** [mne-tools/mne-testing-data#3]
SSS data needs to be re-anonymized after MaxFilter processing.

**Comment by Eric89GXL** [comment]
It puts the subject name back in the data somehow? How could it know it, all traces should have been removed by the original anonimization.

**Comment by agramfort** [comment]
indeed how is that possible?

**Comment by wronk** [comment]
Sorry, it tracks the name of the computer that ran the SSS processing -- not the original subject name.

**Comment by agramfort** [comment]
feel free to close then
