### ISSUE TITLE
Add NIRx fNIRS test data for 15.0 and 15.1

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-testing-data#54]
I am planning to add two more NIRx measurements. The file format is currently 15.2 which was added in #51 and #52 . I will add a 15.1 and 15.0 recording. The four recordings will then cover all versions of the latest file format. Is this ok? Is it the sort of thing you want in this repo? Or is it more appropriate to put elsewhere?

**Comment by larsoner** [comment]
Yes that's in scope for this repo

**Comment by rob-luke** [comment]
Great. I will continue as planned then.
